apiVersion: v1
kind: Service
metadata:
  name: app-analytics-service
  namespace: analytics-service
spec:
  selector:
    app: app-analytics-service
  ports:
  - name: app-analytics-service
    port: 8005
    targetPort: 8005
  type: ClusterIP