services:
  analytics-service:
    build:
      context: .
    container_name: app-analytics-service
    ports:
      - 8005:8005
    environment:
      PORT: ${PORT}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - default
    #depends_on:
    #  evaluation-service:
    #    condition: service_healthy

networks:
  default:
    external: true
    name: togglemaster-network