apiVersion: v1
kind: Service
metadata:
  name: db-auth-service
  namespace: auth-service
spec:
  selector:
    app: db-auth-service
  ports:
  - name: db-auth-service
    port: 7001
    targetPort: 5432
  type: ClusterIP