apiVersion: v1
data:
  AUTH_SERVICE_URL: aHR0cDovL2FwcC1hdXRoLXNlcnZpY2UuYXV0aC1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDE=
  POSTGRES_DB: dGFyZ2V0aW5nX2Ri
  POSTGRES_PASSWORD: dGVzdGVkYnRlc3Rl
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: dGVzdGVkYnRlc3Rl
kind: Secret
metadata:
  name: targeting-db-secret
  namespace: targeting-service
