apiVersion: v1
data:
  AUTH_SERVICE_URL: aHR0cDovL2FwcC1hdXRoLXNlcnZpY2UuYXV0aC1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDE=
  POSTGRES_DB: ZmxhZ19kYg==
  POSTGRES_PASSWORD: dGVzdGVkYnRlc3Rl
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: dGVzdGVkYnRlc3Rl
kind: Secret
metadata:
  name: flag-db-secret
  namespace: flag-service

#kubectl create secret generic flag-db-secret \
#  --from-literal=POSTGRES_USER=testedbteste \
#  --from-literal=POSTGRES_PASSWORD=testedbteste \
#  --from-literal=AUTH_SERVICE_URL='http://app-auth-service.auth-service.svc.cluster.local:8001' \
#  --from-literal=POSTGRES_DB=flag_db \
#  --from-literal=POSTGRES_PORT=5432 \
#  --namespace=flag-service \
#  --dry-run=client -o yaml | kubectl neat