apiVersion: v1
kind: Namespace
metadata:
  name: auth-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: flag-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: targeting-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: evaluation-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics-service