services:
  db-flag-service:
    image: postgres:18.1-alpine3.21
    container_name: db-flag-service
    ports:
      - 7002:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  flag-service:
    build:
      context: .
    container_name: app-flag-service
    ports:
      - 8002:8002
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    networks:
      - default
    depends_on:
      db-flag-service:
        condition: service_healthy

networks:
  default:
    external: true
    name: togglemaster-network