apiVersion: v1
kind: Service
metadata:
  name: app-auth-service
  namespace: auth-service
spec:
  selector:
    app: app-auth-service
  ports:
  - name: app-auth-service
    port: 8001
    targetPort: 8001
  type: ClusterIP