apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-auth-service
  name: app-auth-service
  namespace: auth-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: app-auth-service
  template:
    metadata:
      labels:
        app: app-auth-service
    spec:
      containers:
        - name: app-auth-service 
          image: morganis1411/togglemaster_auth-service:1.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "206Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          #startupProbe:
          #  httpGet:
          #    path: /health
          #    port: 8001
          #  periodSeconds: 5
          #  failureThreshold: 10
          #livenessProbe:
          #  httpGet:
          #    path: "/health"
          #    port: 8001
          #readinessProbe:
          #  httpGet:
          #    path: "/health"
          #    port: 8001
          startupProbe:
            httpGet:
              path: /health
              port: 8001
            failureThreshold: 180   # 180 * 1s = 3 minutos
            periodSeconds: 1

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: auth-db-secret #Credentials to db login and generics
            - secretRef:
                name: auth-db-secret-host #Credential to db login (host)