apiVersion: v1
kind: Service
metadata:
  name: db-targeting-service
  namespace: targeting-service
spec:
  selector:
    app: db-targeting-service
  ports:
  - name: db-targeting-service
    port: 7003
    targetPort: 5432
  type: ClusterIP