apiVersion: v1
kind: Service
metadata:
  name: app-targeting-service
  namespace: targeting-service
spec:
  selector:
    app: app-targeting-service
  ports:
  - name: app-targeting-service
    port: 8003
    targetPort: 8003
  type: ClusterIP