apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-targeting-service
  name: app-targeting-service
  namespace: targeting-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: app-targeting-service
  template:
    metadata:
      labels:
        app: app-targeting-service
    spec:
      containers:
        - name: app-targeting-service 
          image: 449954007039.dkr.ecr.us-east-1.amazonaws.com/togglemaster_targeting-service:1.2.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "206Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8003
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8003
          envFrom:
            - secretRef:
                name: targeting-db-secret #Credentials to db login and generics
            - secretRef:
                name: targeting-db-secret-host #Credential to db login (host)