apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbkBkYi1hdXRoLXNlcnZpY2U6NzAwMS9hdXRoX2Ri
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
  PORT: ODAwMQ==
  POSTGRES_DB: YXV0aF9kYg==
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_USER: YWRtaW4=
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service

#kubectl create secret generic auth-service-secret \
#  --from-literal=POSTGRES_USER=admin \
#  --from-literal=POSTGRES_PASSWORD=admin \
#  --from-literal=POSTGRES_DB=auth_db \
#  --from-literal=DATABASE_URL='postgres://admin:admin@db-auth-service:7001/auth_db' \
#  --from-literal=PORT=8001 \
#  --from-literal=MASTER_KEY=admin-secreto-123 \
#  --namespace=auth-service \
#  --dry-run=client -o yaml | kubectl neat