apiVersion: v1
data:
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
  POSTGRES_DB: YXV0aF9kYg==
  POSTGRES_PASSWORD: dGVzdGVkYnRlc3Rl
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: dGVzdGVkYnRlc3Rl
kind: Secret
metadata:
  name: auth-db-secret
  namespace: auth-service
