apiVersion: v1
data:
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
  POSTGRES_DB: YXV0aF9kYg==
  POSTGRES_PASSWORD: dGVzdGVkYnRlc3Rl
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: dGVzdGVkYnRlc3Rl
kind: Secret
metadata:
  name: auth-db-secret
  namespace: auth-service

#kubectl create secret generic auth-db-secret \
#  --from-literal=POSTGRES_USER=testedbteste \
#  --from-literal=POSTGRES_PASSWORD=testedbteste \
#  --from-literal=POSTGRES_DB=auth_db \
#  --from-literal=POSTGRES_PORT=5432 \
#  --from-literal=MASTER_KEY=admin-secreto-123 \
#  --namespace=auth-service \
#  --dry-run=client -o yaml | kubectl neat