apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-evaluation-service
  name: app-evaluation-service
  namespace: evaluation-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: app-evaluation-service
  template:
    metadata:
      labels:
        app: app-evaluation-service
    spec:
      containers:
        - name: app-evaluation-service 
          image: morganis1411/togglemaster_evaluation-service:1.0
          resources:
            requests:
              cpu: "250m"
              memory: "206Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          #livenessProbe:
          #  httpGet:
          #    path: "/health"
          #    port: 8004
          #readinessProbe:
          #  httpGet:
          #    path: "/health"
          #    port: 8004
          envFrom:
            - secretRef:
                name: evaluation-db-secret #Credentials to db login and generics
            - secretRef:
                name: evaluation-db-secret-host #Credential to db login (host)
              
              