apiVersion: v1
kind: Service
metadata:
  name: app-flag-service
  namespace: flag-service
spec:
  selector:
    app: app-flag-service
  ports:
  - name: app-flag-service
    port: 8002
    targetPort: 8002
  type: ClusterIP