apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-flag-service
  name: app-flag-service
  namespace: flag-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: app-flag-service
  template:
    metadata:
      labels:
        app: app-flag-service
    spec:
      containers:
        - name: app-flag-service 
          image: morganis1411/togglemaster_flag-service:1.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "206Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8002
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8002
          envFrom:
            - secretRef:
                name: flag-db-secret #Credentials to db login and generics
            - secretRef:
                name: flag-db-secret-host #Credential to db login (host)
              