apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-flag-service
  name: app-flag-service
  namespace: flag-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: app-flag-service
  template:
    metadata:
      labels:
        app: app-flag-service
    spec:
      containers:
        - name: app-flag-service 
          image: morganis1411/togglemaster_flag-service:1.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "206Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: flag-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flag-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: flag-db-secret
                  key: POSTGRES_DB
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: flag-db-secret
                  key: AUTH_SERVICE_URL
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: flag-db-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: flag-db-secret-host
                  key: POSTGRES_HOST
              