apiVersion: v1
kind: Service
metadata:
  name: db-evaluation-service
  namespace: evaluation-service
spec:
  selector:
    app: db-evaluation-service
  ports:
  - name: db-evaluation-service
    port: 7004
    targetPort: 6379
  type: ClusterIP