apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-evaluation-service
  name: db-evaluation-service
  namespace: evaluation-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: db-evaluation-service
  template:
    metadata:
      labels:
        app: db-evaluation-service
    spec:
      containers:
        - name: db-evaluation-service 
          image: redis:8.4.0-alpine
          resources:
            requests:
              cpu: "250m"
              memory: "206Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"