apiVersion: v1
data:
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNDQ5OTU0MDA3MDM5L1RvZ2dsZW1hc3Rlci1zcXM=
  FLAG_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDI=
  REDIS_URL: cmVkaXM6Ly9jbHVzdGVyLXJlZGlzLmJ6NG5wYy5uZy4wMDAxLnVzZTEuY2FjaGUuYW1hem9uYXdzLmNvbTo2Mzc5
  SERVICE_API_KEY: dG1fa2V5XzFkMjdjY2M5OWQ4ZjNmMTRlZmU5YjM4NWFkNzcxMWE3ZWFmNjJiM2U4MDMzZGQ1OGExZmQ3MTA4Mjc3OGEwY2Q=
  TARGETING_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDM=
kind: Secret
metadata:
  name: evaluation-db-secret
  namespace: evaluation-service

#kubectl create secret generic evaluation-db-secret \
#  --from-literal=FLAG_SERVICE_URL='http://app-flag-service.flag-service.svc.cluster.local:8002' \
#  --from-literal=TARGETING_SERVICE_URL='http://app-flag-service.flag-service.svc.cluster.local:8003' \
#  --from-literal=SERVICE_API_KEY=tm_key_1d27ccc99d8f3f14efe9b385ad7711a7eaf62b3e8033dd58a1fd71082778a0cd \
#  --from-literal=AWS_SQS_URL=https://sqs.us-east-1.amazonaws.com/449954007039/Togglemaster-sqs \
#  --from-literal=REDIS_URL=redis://cluster-redis.bz4npc.ng.0001.use1.cache.amazonaws.com:6379 \
#  --namespace=evaluation-service \
#  --dry-run=client -o yaml | kubectl neat

#  --from-literal=REDIS_URL=redis://cluster-redis.bz4npc.ng.0001.use1.cache.amazonaws.com:6379 \
#  --from-literal=AWS_SQS_URL='https://sqs.us-east-1.amazonaws.com/904368994695/Toggelmaster-sqs' \
#  --from-literal=AWS_REGION=us-east-1 \

#  --from-literal=AWS_ACCESS_KEY_ID=AKIA5FEEXXGD66MLVOVW \
#  --from-literal=AWS_SECRET_ACCESS_KEY=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 \

#  --from-literal=PORT=8004 \