apiVersion: v1
data:
  FLAG_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDI=
  SERVICE_API_KEY: dG1fa2V5XzY2MjFhMmQwMDM2ODQ1YWY1NmVjOWFjNDVkM2NjOTQ0MjUxOTg0Mzc2YWU3ZjE4MTllZTZjY2UxYzliMjgyYjY=
  TARGETING_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDM=
kind: Secret
metadata:
  name: evaluation-db-secret
  namespace: evaluation-service
