apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: QUtJQTVGRUVYWEdENjZNTFZPVlc=
  AWS_REGION: dXMtZWFzdC0x
  AWS_SECRET_ACCESS_KEY: TVByVFh1OUdsQ2pCT2V3ZGJrd2xDWUhsVEpNczhLSjRYZXMxbUt2Mw==
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vOTA0MzY4OTk0Njk1L1RvZ2dlbG1hc3Rlci1zcXM=
  FLAG_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDI=
  PORT: ODAwNA==
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
  SERVICE_API_KEY: dG1fa2V5XzhmNjhkOWY1YzVlNDUzNTk4MDRmMGViMjA4MGNmYWNiNjg3NTAwYWQzM2MyMmE2MWYzMzdlN2U2Zjc3ZjRjY2U=
  TARGETING_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDM=
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service

#kubectl create secret generic evaluation-service-secret \
#  --from-literal=REDIS_URL=redis://db-evaluation-service:7004 \
#  --from-literal=FLAG_SERVICE_URL='http://app-flag-service.flag-service.svc.cluster.local:8002' \
#  --from-literal=TARGETING_SERVICE_URL='http://app-flag-service.flag-service.svc.cluster.local:8003' \
#  --from-literal=AWS_SQS_URL='https://sqs.us-east-1.amazonaws.com/904368994695/Toggelmaster-sqs' \
#  --from-literal=PORT=8004 \
#  --from-literal=AWS_REGION=us-east-1 \
#  --from-literal=AWS_ACCESS_KEY_ID=AKIA5FEEXXGD66MLVOVW \
#  --from-literal=AWS_SECRET_ACCESS_KEY=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 \
#  --from-literal=SERVICE_API_KEY=tm_key_8f68d9f5c5e45359804f0eb2080cfacb687500ad33c22a61f337e7e6f77f4cce \
#  --namespace=evaluation-service \
#  --dry-run=client -o yaml | kubectl neat