apiVersion: v1
data:
  FLAG_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDI=
  SERVICE_API_KEY: dG1fa2V5XzY2MjFhMmQwMDM2ODQ1YWY1NmVjOWFjNDVkM2NjOTQ0MjUxOTg0Mzc2YWU3ZjE4MTllZTZjY2UxYzliMjgyYjY=
  TARGETING_SERVICE_URL: aHR0cDovL2FwcC1mbGFnLXNlcnZpY2UuZmxhZy1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDM=
kind: Secret
metadata:
  name: evaluation-db-secret
  namespace: evaluation-service

#kubectl create secret generic evaluation-db-secret \
#  --from-literal=FLAG_SERVICE_URL='http://app-flag-service.flag-service.svc.cluster.local:8002' \
#  --from-literal=TARGETING_SERVICE_URL='http://app-targeting-service.targeting-service.svc.cluster.local:8003' \
#  --from-literal=SERVICE_API_KEY=tm_key_1ef7e5f8ed00afc4ddd7ed7f6c3734072f6e79180ea95e72688e9cba426675f2 \
#  --namespace=evaluation-service \
#  --dry-run=client -o yaml | kubectl neat

#  --from-literal=REDIS_URL=redis://cluster-redis.bz4npc.ng.0001.use1.cache.amazonaws.com:6379 \
#  --from-literal=AWS_SQS_URL='https://sqs.us-east-1.amazonaws.com/904368994695/Toggelmaster-sqs' \
#  --from-literal=AWS_REGION=us-east-1 \

#  --from-literal=AWS_ACCESS_KEY_ID=AKIA5FEEXXGD66MLVOVW \
#  --from-literal=AWS_SECRET_ACCESS_KEY=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 \

#  --from-literal=PORT=8004 \